### ISSUE TITLE
安装并执行 CocCommand rainbow-fart.enable后写js没有声音

### ISSUE THREAD

**Issue by tzngit** [iamcco/coc-rainbow-fart#2]
os: ubuntu 18.04 server版
node:  V12.18.1
nvim: v0.5.0-567-g4496628c1(build from source)

coc.nvim是用vimplug安装，release版本：
Plug 'neoclide/coc.nvim', {'branch': 'release'}

CocList extensions 输出如下：
  * coc-rainbow-fart 1.1.3 ~/.config/coc/extensions/node_modules/coc-rainbow-fart
  + coc-tsserver 1.5.2 ~/.config/coc/extensions/node_modules/coc-tsserver
  + coc-lua 0.1.1 ~/.config/coc/extensions/node_modules/coc-lua
  + coc-html 1.2.4 ~/.config/coc/extensions/node_modules/coc-html

**Comment by tzngit** [comment]
我知道了，因为server版本没有声卡....
I think I konw the reason, ubuntu server do not have a audio card

**Comment by iamcco** [comment]
可以看看插件的 output channel，另一个可能是下载的 ffplay 不能用

**Comment by Neur1n** [comment]
output channel里没有rainbow-fart的channel请问是什么原因

**Comment by iamcco** [comment]
@Neur1n 设置 `"rainbow-fart.trace.server": "verbose"`

**Comment by ronylee11** [comment]
> 可以看看插件的 output channel，另一个可能是下载的 ffplay 不能用

感谢提示！
我把 ~/.config/coc/extensions/coc-rainbow-fart-data/ffplay 删除了，用 ln -s /bin/ffplay ffplay 做了个symlink链接本地的ffplay
现在莫满提了！
