### ISSUE TITLE
How to enable external voicepack?

### ISSUE THREAD

**Issue by ronylee11** [iamcco/coc-rainbow-fart#21]
Hi!
I just imported a Yukino Yukinoshita voicepack, which is already been proved to be working in VSCode Rainbow Fart
How can i enable it in coc-rainbow-fart?
I've added 
"rainbow-fart.voice-packages": [
  "~/Downloads/rbf_voicepack/Yukinoshita.Yukino-1.0.0.zip"
],
in my ~/.config/nvim/coc-settings.json

Here is what i see when i run :CocList VoicePackages
![2022-05-24-135608_1366x183_scrot](https://user-images.githubusercontent.com/64385071/169959023-8fb6b86f-b3d3-4c99-ace0-5495b545329a.png)

你好！
我刚输入了一个雪乃的语音包，
在 ~/.config/nvim/coc-settings.json 里加了

"rainbow-fart.voice-packages": [
  "~/Downloads/rbf_voicepack/Yukinoshita.Yukino-1.0.0.zip"
],

:CocList VoicePackages  的时候却显示Disabled,我该怎么启用的同时取消默认语音包?
![2022-05-24-135608_1366x183_scrot](https://user-images.githubusercontent.com/64385071/169959023-8fb6b86f-b3d3-4c99-ace0-5495b545329a.png)

**Comment by iamcco** [comment]
不支持 zip 吧，解压下

**Comment by ronylee11** [comment]
抱歉好像重复了，我刚看到 #4

解压后在 coc-settings.json 里加入了
"rainbow-fart.locale": ["jp"],
"rainbow-fart.voice-packages": ["$HOME/Downloads/yukino"],
"rainbow-fart.disable-voice-packages": []
 
然后就成功启用了！
感谢回复 ^-^
