### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by fgheng** [iamcco/coc-rainbow-fart#3]
是不是安装完就可以了，还需要配置么？安装完没有声音，提示下面的内容。
![image](https://user-images.githubusercontent.com/50551377/85283521-1529c180-b4c0-11ea-8899-d6023dfcb053.png)

**Comment by iamcco** [comment]
你下这个替换下 https://github.com/vot/ffbinaries-prebuilt/releases/download/v3.2/ffplay-3.2.2-linux-64.zip 替换下报错路径里面的 ffplay，看下能不能用，现在下载的是 32 位的。

**Comment by iamcco** [comment]
如果可以用我就更新下，或者配置 `rainbow-fart.ffplay` 为本地的 ffplay

**Comment by fgheng** [comment]
我替换了，倒是不报错了，但是没有声音，是我哪个姿势不对么？我看readme也不需要配置什么呀。

**Comment by fgheng** [comment]
使用新发的那个ffplay不报错了，但是没有声音，配置`rainbow-fart.ffplay`为本地的ffplay之后解决问题

**Comment by iamcco** [comment]
破案了，linux下那个不是static build的

https://github.com/vot/ffbinaries-prebuilt/issues/7
