### ISSUE TITLE
似乎不支持vscode版插件的语音包格式？

### ISSUE THREAD

**Issue by dianlujitao** [iamcco/coc-rainbow-fart#4]
例如 https://github.com/zthxxx/kugimiya-rainbow-fart 的1.0及更新版本
Ref: https://github.com/SaekiRaku/vscode-rainbow-fart/blob/master/docs/zh/voice-packages.md

**Comment by iamcco** [comment]
支持的，确保你设置对了

- `"rainbow-fart.locale": ["zh"]` 配置启用的语音包语言
- `"rainbow-fart.voice-packages: []" 确保引入了第三方的语音包

**Comment by iamcco** [comment]
还不支持引入zip语音包，记得解压下

**Comment by dianlujitao** [comment]
我的配置是这样，但放出来的还是默认的中文语音，`:CocList VoicePackages` 报错 `[coc.nvim] List VoicePackages not found`

```json
  "rainbow-fart.voice-packages": [
    "$HOME/kugimiya-voice"
  ],
```
```
❯ ls ~/kugimiya-voice
avatars  CHANGELOG.md  manifest.json  README.md  resource.csv  voices
```
哪里有问题么（

**Comment by iamcco** [comment]
上面说了 `"rainbow-fart.locale": ["zh"]` 设置了么？你把你要引入的语言包的语言启用了么？

还有关于报错 `:CocList VoicePackages`，设置 `"rainbow-fart.trace.server": "verbose"` 查看 output channel 看看

**Comment by iamcco** [comment]
还有如果你有多个语音包都启用，一次会随机选择一条播放的

**Comment by dianlujitao** [comment]
感谢提醒，locale改成jp就能用了。

不过`:CocList VoicePackages`仍然打不开，直接用`:CocList`在备选里也没有`VoicePackages`，rainbow-fart的output channel是空的。

**Comment by iamcco** [comment]
> 不过:CocList VoicePackages仍然打不开，直接用:CocList在备选里也没有VoicePackages，rainbow-fart的output channel是空的。

这个就很诡异了，我这里没法复现
